import woo.std;
import woo.vm;
import woo.debug;

import test_tool;

namespace test_exception
{
    func main()
    {
        // todo;
    }
}

test_function("test_exception.main", test_exception::main);